### ISSUE TITLE
Idea: put all translated content into the CMS

### ISSUE THREAD

**Issue by satazor** [moxystudio/next-with-moxy#2]
There are two types of copy:

- Static, coming from JSON files within the source code
- Editable, coming from the CMS

We may change our approach so that both these types all come from the CMS. This has some benefits, such as making it easier to add a new language/locale.

Discuss!

**Comment by jdiogopeixoto** [comment]
We can close this since it is covered in the CMS recipes, correct?

**Comment by satazor** [comment]
Correct, thanks for noticing it!
