### ISSUE TITLE
Add tests for the boilerplate components

### ISSUE THREAD

**Issue by satazor** [moxystudio/next-with-moxy#32]
Now that we have a coverage percentage of >= 80%, the CI will fail because of this constraint.

To solve this, we should:

- Implement tests so that coverage is >= 80% (ideally 100%)
- Setup travis & codecov
- Add our typical "build passing" and "coverage"  badges to the README
- Add "Remove `.travis.yml`" to the list of files to delete to our `instructions.md` doc file

**Comment by ritazoliveira** [comment]
Going to close this issue since the changes asked were already made and merged.
