### ISSUE TITLE
Highlighted links aren't distinguished from normal highlighted text.

### ISSUE THREAD

**Issue by threequartersjohn** [moxystudio/next-with-moxy#35]
When "backticking" a link `like this`, no styling indicates it being a link. The only way to know that a link is a link before a click is with hovering. Links should be visually distinct form normal text so readers can visually parse interactable elements. 

You can find an example of this in [Internationalization](https://next-with.moxy.tech/docs/what-is-included/internationalization), with `react-intl`.

**Comment by satazor** [comment]
Fixed!
