### ISSUE TITLE
Implement HTTP2

### ISSUE THREAD

**Issue by threequartersjohn** [moxystudio/next-with-moxy#5]
Express does not currently support HTTP2 ([check here](https://github.com/expressjs/express/pull/3730) for their PR on this topic), but one possible solution is using [spdy](https://github.com/spdy-http2/node-spdy) together with express.

**Comment by rafaelramalho19** [comment]
Koa supports HTTP2, and since I'm currently migrating the plugins to be compatible with Koa, I think this will be a non-issue 😄

**Comment by satazor** [comment]
Closing this as we are no longer shipping with a custom server, and maybe Next.js will implement this in the future. Neverthless, we use HTTP 2 in upstream servers, so it's a non-issue.
